### ISSUE TITLE
Balance 0 even with known non-zero UTXOs

### ISSUE THREAD

**Issue by taxmeifyoucan** [samotari/pay-no-way#21] opened 2021-02-21 00:46 UTC
New transactions won't show in the app, only the very first one is in the history. 2 other, sent and received are missing, balance is wrong. Maybe issue with Electrum server? Tested on Android 10

**Comment by chill117** [comment] 2021-02-23 10:06
Fees are quite high now. I hadn't tested the app under these conditions. Bitcoin nodes have different rules for accepting and relaying transactions based on fee rate. If the mempool is over 300 MB then nodes might start rejecting (or not relaying) transactions with fees below a certain threshold. Currently that threshold might be above 8 sats / vbyte. In addition, ElectrumX servers could be behind a few blocks or might not see all the unconfirmed transactions.

**Comment by taxmeifyoucan** [comment] 2021-02-23 14:47
Sorry, forgot to mention that missing transactions are already confirmed for days so they should be there no matter what is happening in the mempool.

**Comment by chill117** [comment] 2021-02-24 10:45
So after investigation, it looks like this could be caused by no connection to any ElectrumX server. The balance is calculated from your address' current UTXOs. So if the app cannot query for the UTXOs, then the balance will be 0. I'll create a new issues that will hopefully fix this.

**Comment by chill117** [comment] 2021-03-11 09:36
As previously said, this bug was caused by the app relying on ElectrumX servers for blockchain-related querying (e.g for an address/scripthash's UTXOs). The app has been migrated to web services (esplora, mempool) APIs. It's possible to self-host an instance of one of the supported web services. These changes will be included in the next release of the app (v2.0.0).

**Closed by chill117** 2021-03-11 09:36 UTC
Labels: bug
